### ISSUE TITLE
kmean todo's

### ISSUE THREAD

**Issue by disa-mhembere** [flashxio/FlashX#162]
- [x] Prune in init engine
- [x] Fix prune stats reporting
- [x] Get feed-in init-centers working
- [x] Minimize sem_kmeans vertex state
- [x] Try to reduce I/O in by doing lemma 2 test in run
- [x] base class for cluster so prev_mean is gone for full
- [x] sqrt test for equiv distance metric
- [x] Fix test_sem_kmeans since refactor
- [x] Prune non-minimized tri_sem init for fairness
- [x] extern globals in sem_kmeans.h
